### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Asterix1002** [sunnankar/bm#111]
Hi! I'm from Argentina. Would be useful if I try to translate some docs to Spanish? If yes, should I write something special in the docs' name?

**Comment by yosoyquiensoy** [comment]
I am an experienced translator to Spanish and also global moderator for www.diyrc.co.uk.   I'd be happy to help.

**Comment by lilkamzbest** [comment]
Hi! I am from Africa! Should I help you to translate some docs to french??

**Comment by Asterix1002** [comment]
yosoyquiensoy, is there a way we can talk to help us each other in some translations? I´m new here...

**Comment by yosoyquiensoy** [comment]
Hello,I offered my service as a translator, but until now I haven't been contacted by anybody and no material to translate has been provided to me.so I don't know what follows or what to do.

**Comment by yasefiruzei** [comment]
hello
i,m in Iran
i,m Newcomer
but you have to know we have to Help this service
This service helps the world
I continue
 You keep going too

**Comment by Felucho** [comment]
Hi, I am from Venezuela.  I can help you to translate to spanish some docs in your project but I do not have too much experience how to help.Thanks . Best regards.

**Comment by Mona288** [comment]
I studied IT and I am good at translating technical stuff
I could translate to Arabic 
Please tell me how can I contribute and where can I get the text from

Thanjs

**Comment by saeed-m-1978** [comment]
Dear Sir
‎‎‎My name is Saeed Mohammadpour, a senior
developer in Iran, who recently has been interested in Bitcoin Minning. 
I'm much eager to introduce your work to Persian speakers.
Therefore, I will be greatly obliged if you send me information enough about your conditions for translators.
Thanks a lot.

With warm regards,
Saeed Mohammadpour

**Comment by Hehehenky** [comment]
I’ll translate into Swedish

**Comment by esthefmari** [comment]
Hello there, i'd like to be useful to you guys, i could translate from English to Spanish in a non-robotic way... like, easy to read, so, because my mother language is Spanish i can read it and write it fluently

Let me know what i can help with, but, of course i'd have a price for it.... i'd like to do it as a part time job someday.

Thanks for reading, have a great day!

**Comment by Nomade23** [comment]
Hi. French here. Totally bilingual in english. Fluent in spanish and honorable level of dutch and italien. Wish to help since I have plenty of free time.  Also mining ethereum and litecoin

**Comment by rizkyfaldy98** [comment]
Hello. My name is Faldy and I am from Indonesia. It's been a while since I learned into Bitcoin and I think want to contribute and be a part of this project as an Indonesian translator. I'd be happy if I can be a part of this project and translate all of this website content to educate my people in Indonesia about Bitcoin and mining tips. If you don't mind you may contact me on email. My email is rizkyfaldy98@gmail.com.

I am sorry about my non formal email because basically, I just started to build a startup with my friends in my country.

And I hope you can tell me and describe me more about this project and what should I do to make this site more compatible for Indonesian. And I am ready to be your partner.

Thank you.

**Comment by jvmgil** [comment]
hey i'm brazilian, i can translate it into portuguese

**Comment by Catalina40k** [comment]
Good afternoon! I'm Kathia from Bolivia and I need your help as I would be to write for the good of the people in my country. Thank you

**Comment by OscarReichert** [comment]
Hello

I'm a smart and industrious 26 year old guy working as a teacher in Finland. I think there are lots of people getting interested in Bitcoin in our highly technological society, because I've been listening carefully. Feel free to contact me for additional information about me, because I've got some spare time and energy on my hands, and I'm interested in hearing what you would have to offer for top-notch translations.

Thanks!

**Comment by Felucho** [comment]
Sorry this a test. Confirm.Thanks
--------------------------------------------
El Lun 12/2/18, OscarReichert <notifications@github.com> escribió:

 Asunto: Re: [sunnankar/bm] Translations (#111)
 Para: "sunnankar/bm" <bm@noreply.github.com>
 Cc: "FELIX VARGAS" <Icabaru@yahoo.com>, "Comment" <comment@noreply.github.com>
 Fecha: Lunes 12 de Febrero de 2018, 22:58
 
 Hello
 I'm a smart and industrious 26 year old guy working
 as a teacher in Finland. I think there are lots of people
 getting interested in Bitcoin in our highly technological
 society, because I've been listening carefully. Feel
 free to contact me for additional information about me,
 because I've got some spare time and energy on my hands,
 and I'm interested in hearing what you would have to
 offer for top-notch translations.
 Thanks!
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by OscarReichert** [comment]
Hi

Take this as a confirmation!

Oscar

ke 14.2.2018 klo 0.19 FELIX VARGAS <notifications@github.com> kirjoitti:

> Sorry this a test. Confirm.Thanks
> --------------------------------------------

**Comment by yeesan** [comment]
Hi, I'm new here. I am Chinese, can write both Traditional Chinese and Simplify Chinese, and with technical background. Do you need translation (still)? Please reply or email me: yeesan2004@gmail.com. I am also interested in any chat group.-Victoria

**Comment by karam-nashwan** [comment]
Hello I'm karam, Computer Engineer and I'm pleased to translate your content about bitcoin to Arabic language. It would be great to have a copy of your efforts in huge language like arabic 
If interested please email at karam.nashwan@gmail.com
 Thanks

**Comment by bithostel-dev** [comment]
Hi! I'm from Brazil. Would be useful if I translate the website to (BR)Brazilian Portuguese?

regards.
